### ISSUE TITLE
Code coverage with mochify-istanbul

### ISSUE THREAD

**Issue by ussuritiger** [decipherinc/grunt-mochify#4]
Hi, first of all thanks a lot for a nice Grunt module. Are you going to implement support of code coverage using for example mochify-istanbul? I think that could be very useful.

**Comment by boneskull** [comment]
if Mochify can do it, then this module can do it.   checkout [this doc](https://github.com/mantoni/mochify.js/blob/master/README.md) for valid options.  let me know if you are having trouble.
